name: Branch Protection Workflow

on:
  push:
    branches:
      - main
      - development

jobs:
  branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Verify branch protection rules
        run: |
          echo "Ensure PRs and CI checks are required for main and development branches."
          exit 0
